import test from 'node:test';
import {spawnSync} from 'node:child_process';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DurableStore,validateEvidence} from '../src/controller/durable-store.mjs';
import {RunController} from '../src/controller/run-controller.mjs';
const config=JSON.parse(readFileSync(new URL('../config/pilot.example.json',import.meta.url)));
const payload={materiality:'M2',status:'Draft',humanDecisionOwner:'Alec Gardner',sources:[{id:'NEE-AI-SRC-TEST',url:'https://example.com',contentHash:'abc',retrievedAt:'2026-10-07T00:00:00Z'}],claims:[{id:'NEE-AI-CLM-TEST',text:'An attributed test claim.',type:'attributed claim',verificationStatus:'unresolved',humanApprovalRequired:true}],links:[{claimId:'NEE-AI-CLM-TEST',sourceId:'NEE-AI-SRC-TEST',role:'supporting',locator:'L16'}]};
function fixture(t,c=config){const directory=mkdtempSync(join(tmpdir(),'nexus-run-'));let now=1000;const path=join(directory,'runs.sqlite'),store=new DurableStore(path,{now:()=>now});t.after(()=>{try{store.close()}catch{}rmSync(directory,{recursive:true,force:true})});const run=store.create({config:c,windowStart:'2026-10-01',windowEnd:'2026-10-08'});return {store,path,run,token:store.acquire(run.id,'worker1'),advance:ms=>now+=ms,clock:()=>now}}
function validating(f){for(const stage of ['researching','verifying','challenging','drafting','validating'])f.store.checkpoint(f.token,{expectedVersion:f.store.get(f.run.id).version,stage,pendingWork:[]})}
test('window is unique and configuration pinned',t=>{const f=fixture(t);const again=f.store.create({config,windowStart:'2026-10-01T00:00:00Z',windowEnd:'2026-10-08T00:00:00Z'});assert.equal(again.id,f.run.id);const c=structuredClone(config);c.limits.research_calls=59;assert.throws(()=>f.store.create({config:c,windowStart:'2026-10-01',windowEnd:'2026-10-08'}),/configuration_changed/)});
test('checkpoint and usage survive reopening',t=>{const f=fixture(t);f.store.checkpoint(f.token,{expectedVersion:0,stage:'researching',pendingWork:['verify']});f.store.reserve(f.token,{key:'s1',tool:'search_public_web',input:{q:'AI'}});f.store.close();const reopened=new DurableStore(f.path,{now:f.clock});assert.equal(reopened.get(f.run.id).calls,1);assert.deepEqual(reopened.get(f.run.id).checkpoint.pendingWork,['verify']);reopened.close()});
test('competing connections cannot acquire same live lease',t=>{const f=fixture(t);const second=new DurableStore(f.path,{now:f.clock});assert.throws(()=>second.acquire(f.run.id,'worker2'),/lease_busy/);second.close()});
test('expired worker fenced out after takeover',t=>{const f=fixture(t);f.advance(30001);const next=f.store.acquire(f.run.id,'worker2');assert.throws(()=>f.store.reserve(f.token,{key:'stale',tool:'search_public_web',input:{}}),/lease_lost/);assert.equal(next.fence,2)});
test('checkpoint compare-and-swap and ordering',t=>{const f=fixture(t);assert.throws(()=>f.store.checkpoint(f.token,{expectedVersion:0,stage:'drafting',pendingWork:[]}),/invalid_transition/);f.store.checkpoint(f.token,{expectedVersion:0,stage:'researching',pendingWork:[]});assert.throws(()=>f.store.checkpoint(f.token,{expectedVersion:0,stage:'verifying',pendingWork:[]}),/checkpoint_conflict/)});
test('completed call cached on retry, changed input rejected',async t=>{const f=fixture(t);let calls=0;const c=new RunController({...f,tools:{search_public_web:async()=>{calls++;return ['url']}}});const action={key:'search',tool:'search_public_web',input:{q:'AI'}};assert.deepEqual(await c.call(action),['url']);assert.deepEqual(await c.call(action),['url']);assert.equal(calls,1);await assert.rejects(c.call({...action,input:{q:'other'}}),/idempotency_conflict/)});
test('retry and call allowance survive uncertain read',t=>{const c=structuredClone(config);c.limits.research_calls=2;const f=fixture(t,c);const a={key:'search',tool:'search_public_web',input:{}};f.store.reserve(f.token,a);f.store.reserve(f.token,a);assert.throws(()=>f.store.reserve(f.token,a),/allowance_exhausted/)});
test('uncertain write cannot be silently repeated',t=>{const f=fixture(t),a={key:'write',tool:'append_evidence',input:{}};f.store.reserve(f.token,a);assert.throws(()=>f.store.reserve(f.token,a),/uncertain_write_requires_reconciliation/)});
test('denied/unknown paid tools never reserve calls',t=>{const f=fixture(t);assert.throws(()=>f.store.reserve(f.token,{key:'email',tool:'send_email',input:{}}),/tool_denied/);assert.throws(()=>f.store.reserve(f.token,{key:'search',tool:'search_public_web',input:{},costAudCents:null}),/paid_or_unknown/);assert.equal(f.store.get(f.run.id).calls,0)});
test('cancellation and deadline prevent dispatch',t=>{const f=fixture(t);f.store.cancel(f.run.id);assert.throws(()=>f.store.reserve(f.token,{key:'search',tool:'search_public_web',input:{}}),/cancelled/)});
test('restart retains absolute deadline',t=>{const f=fixture(t);f.advance(config.limits.timeout_seconds*1000);assert.throws(()=>f.store.heartbeat(f.token),/lease_lost|deadline/);assert.equal(f.store.get(f.run.id).deadline,1201000)});
test('partial does not advance cutoff',t=>{const f=fixture(t);f.store.partial(f.token,'source_unavailable');assert.equal(f.store.cutoff(config.agent_id),null);assert.equal(f.store.get(f.run.id).status,'partial')});
test('evidence queue idempotent and prohibits approved claims',t=>{const f=fixture(t);const id=f.store.queueEvidence(f.token,{key:'delivery-1',payload});assert.equal(f.store.queueEvidence(f.token,{key:'delivery-1',payload}),id);const changed=structuredClone(payload);changed.claims[0].verificationStatus='verified';assert.throws(()=>validateEvidence(changed),/claim_approval_forbidden/)});
test('unverified register never receives evidence',async t=>{const f=fixture(t);f.store.queueEvidence(f.token,{key:'delivery-1',payload});const c=new RunController({...f,register:{schemaVerified:false,appendEvidence:async()=>assert.fail()}});await assert.rejects(c.flushEvidence(),/register_connection_unverified/);assert.equal(f.store.pendingEvidence(f.run.id).length,1)});
test('lost delivery acknowledgement retried with same key and receipt',async t=>{const f=fixture(t);f.store.queueEvidence(f.token,{key:'delivery-1',payload});let attempts=0,remoteWrites=0;const received=new Map();const register={schemaVerified:true,supportsIdempotency:true,appendEvidence:async input=>{attempts++;if(!received.has(input.idempotencyKey)){remoteWrites++;received.set(input.idempotencyKey,{idempotencyKey:input.idempotencyKey,payloadHash:input.payloadHash,recordIds:['register-record']})}if(attempts===1)throw new Error('lost ack');return received.get(input.idempotencyKey)}};const c=new RunController({...f,register});await assert.rejects(c.flushEvidence(),/register_delivery_pending/);await c.flushEvidence();assert.equal(remoteWrites,1);assert.equal(f.store.pendingEvidence(f.run.id).length,0)});
test('pending evidence blocks ready report; validated draft advances cutoff atomically',async t=>{const f=fixture(t);f.store.queueEvidence(f.token,{key:'delivery-1',payload});validating(f);const report={content:'Draft report for review.',validation:{passed:true,evidenceReviewed:true}};assert.throws(()=>f.store.saveReady(f.token,report),/evidence_delivery_pending/);const item=f.store.pendingEvidence(f.run.id)[0];f.store.delivered(f.token,item.id,{idempotencyKey:item.delivery_key,payloadHash:item.payload_hash,recordIds:['record']});const saved=f.store.saveReady(f.token,report);assert.equal(saved.status,'draft');assert.equal(f.store.cutoff(config.agent_id),'2026-10-08T00:00:00.000Z');assert.equal(f.store.get(f.run.id).status,'ready_for_review')});
test('in-flight cancelled run aborts and cannot save completion',async t=>{const f=fixture(t);const c=new RunController({...f,tools:{search_public_web:async(_input,{signal})=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}))}});const pending=c.call({key:'slow',tool:'search_public_web',input:{}});f.store.cancel(f.run.id);await assert.rejects(pending,/aborted|run_stopped/);assert.equal(f.store.get(f.run.id).status,'cancelled')});

test('forced process kill preserves checkpoint and fences crashed worker',t=>{
 const f=fixture(t);f.store.release(f.token);
 const source=`import {DurableStore} from './src/controller/durable-store.mjs'; const s=new DurableStore(${JSON.stringify(f.path)},{now:()=>1000}); const token=s.acquire(${JSON.stringify(f.run.id)},'crash-worker'); s.checkpoint(token,{expectedVersion:0,stage:'researching',pendingWork:['verify-original']});s.reserve(token,{key:'crash-search',tool:'search_public_web',input:{q:'AI'}});process.kill(process.pid,'SIGKILL');`;
 const killed=spawnSync(process.execPath,['--input-type=module','-e',source],{cwd:new URL('..',import.meta.url)});assert.equal(killed.signal,'SIGKILL');f.advance(30001);const token=f.store.acquire(f.run.id,'recovery-worker');assert.equal(token.fence,3);assert.deepEqual(f.store.get(f.run.id).checkpoint.pendingWork,['verify-original']);assert.equal(f.store.get(f.run.id).calls,1);
});

test('partial recovery resumes saved stage without refreshing deadline',t=>{const f=fixture(t);f.store.checkpoint(f.token,{expectedVersion:0,stage:'researching',pendingWork:['verify']});const deadline=f.store.get(f.run.id).deadline;f.store.partial(f.token,'temporary_outage');f.store.acquire(f.run.id,'resumed-worker');assert.equal(f.store.get(f.run.id).status,'researching');assert.equal(f.store.get(f.run.id).deadline,deadline)});
