import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DurableStore} from '../src/controller/durable-store.mjs';
import {draftReport,validateReport,digest} from '../src/reporting/report.mjs';
import {ReportReview} from '../src/review/report-review.mjs';
import {createReviewServer,reviewPage} from '../src/review/review-server.mjs';
const config=JSON.parse(readFileSync(new URL('../config/pilot.example.json',import.meta.url)));
const now=Date.parse('2026-10-08T00:00:00Z');
const human={authenticated:true,actorType:'human',subject:'verified-owner-test',owner:'Alec Gardner',scopes:['workplace_report_review']};
function fixture(t){
 const dir=mkdtempSync(join(tmpdir(),'nexus-review-')),store=new DurableStore(join(dir,'state.sqlite'),{now:()=>now});t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true})});
 const run=store.create({config,windowStart:'2026-10-01',windowEnd:'2026-10-08'}),token=store.acquire(run.id,'test-host');
 const evidence={sources:[{id:'s1',title:'Original source',authorIssuingBody:'Research authors',url:'https://example.com/research',publicationDate:'2026-10-03',contentHash:'hash-1',retrievalStatus:'retrieved'}],claims:[{id:'c1',text:'The authors report workplace evidence within the study context.',type:'attributed claim',verificationStatus:'provisionally supported',limitations:'One context only'}],links:[{claimId:'c1',sourceId:'s1',role:'supporting'}]};
 const options={selectedItems:[{id:'item1',title:'Workplace evidence',organisation:'Research institute',category:'research_and_evidence',publicationDate:'2026-10-03',announcementDate:null,rankingRationale:'Relevant primary research.',workplaceRelevance:'Consider the scope before adopting.',limitations:'One study context; cannot generalise.',claimIds:['c1'],sourceIds:['s1']}],events:[],practicalAction:'Review the study context before reuse.',evidenceGaps:['No suitable Australian development in this test.'],quietWeekReason:'Only one suitable development passed verification.'};
 const report=draftReport({run,...options});
 const attest=(r=report,e=evidence)=>({reportHash:digest(r),evidenceHash:digest(e),australianSearchCompleted:true,challengeCompleted:true,itemChecks:{item1:{itemHash:digest(r.items[0]),datesChecked:true,editorialWordingReviewed:true}},claimChecks:{c1:{claimHash:digest(e.claims[0]),supportsWording:true}},sourceChecks:{s1:{contentHash:e.sources[0].contentHash,linkResolved:true,checkedAt:new Date(now).toISOString()}}});
 const review=new ReportReview({store,authenticate:async context=>context,now:()=>now});return {store,run,token,evidence,options,report,attest,review};
}
test('quiet-week draft passes without invented padding',t=>{const f=fixture(t),v=validateReport(f.report,{...f,attestation:f.attest(),now});assert.equal(v.passed,true);assert.ok(v.warnings.includes('short_report_justified_by_quiet_week'));assert.ok(v.content.includes('Attributed claim:'))});
test('unregistered claim cannot enter report',t=>{const f=fixture(t);f.report.items[0].claimIds=['made-up'];assert.equal(validateReport(f.report,{...f,attestation:f.attest(),now}).passed,false)});
test('unresolved claim blocks shortlist',t=>{const f=fixture(t);f.evidence.claims[0].verificationStatus='unresolved';assert.ok(validateReport(f.report,{...f,attestation:f.attest(),now}).errors.includes('unresolved_claim_in_shortlist'))});
test('changed claim requires fresh wording review',t=>{const f=fixture(t),a=f.attest();f.evidence.claims[0].text='Much stronger causal wording';assert.ok(validateReport(f.report,{...f,attestation:a,now}).errors.includes('claim_semantic_review_required'))});
test('missing Australian/challenge checks block report',t=>{const f=fixture(t),a=f.attest();a.australianSearchCompleted=false;a.challengeCompleted=false;const v=validateReport(f.report,{...f,attestation:a,now});assert.ok(v.errors.includes('australian_search_required'));assert.ok(v.errors.includes('challenge_review_required'))});
test('old item needs explicit exception',t=>{const f=fixture(t);f.report.items[0].publicationDate='2025-01-01';assert.ok(validateReport(f.report,{...f,attestation:f.attest(),now}).errors.includes('out_of_window'))});
test('stale link checks block report',t=>{const f=fixture(t),a=f.attest();a.sourceChecks.s1.checkedAt='2026-10-01T00:00:00Z';assert.ok(validateReport(f.report,{...f,attestation:a,now}).errors.includes('source_validation_required'))});
test('event timezone/date/registration verified independently',t=>{const f=fixture(t);f.report.events=[{id:'event1',title:'Workshop',startsAt:'2026-10-09T09:00:00+11:00',timezone:'Australia/Sydney',formatLocation:'Online',registrationUrl:'https://example.com/event'}];assert.ok(validateReport(f.report,{...f,attestation:f.attest(),now}).errors.includes('event_verification_required'))});
test('model actor cannot approve',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});await assert.rejects(f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:{...human,actorType:'agent'}}),/denied/)});
test('human approval tied to exact version and hash',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});await assert.rejects(f.review.decide(r.id,{expectedHash:'wrong',decision:'approve',authContext:human}),/stale/);const d=await f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:human});assert.equal(d.status,'approved');assert.equal(d.published,false)});
test('revision after approval requires new decision; old history preserved',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});await f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:human});f.report.practicalAction='Review new evidence before reuse.';const newer=await f.review.revise(r.id,{expectedHash:r.hash,report:f.report,evidence:f.evidence,attestation:f.attest(),authContext:human});assert.equal(newer.status,'ready_for_review');assert.equal(f.review.get(r.id).status,'approved');await assert.rejects(f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:human}),/superseded/)});
test('failed validation cannot be approved',async t=>{const f=fixture(t),a=f.attest();a.challengeCompleted=false;const r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:a});await assert.rejects(f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:human}),/validation_failed/)});
test('request changes records comments',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});const d=await f.review.decide(r.id,{expectedHash:r.hash,decision:'request_changes',comments:'Check population scope.',authContext:human});assert.equal(d.status,'changes_requested')});
test('review page escapes injected source text',t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});const record=f.review.get(r.id);record.content='<script>alert(1)</script>';assert.ok(!reviewPage(record).includes('<script>'))});
test('review endpoint enforces origin and human identity',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});const server=createReviewServer({review:f.review,authenticateRequest:async req=>req.headers['x-test-identity']==='human'?human:null,origin:'http://127.0.0.1'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());const url=`http://127.0.0.1:${server.address().port}/reports/${r.id}`;assert.equal((await fetch(url)).status,403);assert.equal((await fetch(url,{headers:{'x-test-identity':'human'}})).status,200);assert.equal((await fetch(url+'/decision',{method:'POST',headers:{'x-test-identity':'human','content-type':'application/x-www-form-urlencoded',origin:'https://hostile.example'},body:new URLSearchParams({expectedHash:r.hash,decision:'approve'})})).status,403);assert.equal(f.review.get(r.id).status,'ready_for_review')});

test('source-attested report is saved and run cutoff advances before publication approval',t=>{const f=fixture(t);const r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});for(const stage of ['researching','verifying','challenging','drafting','validating'])f.store.checkpoint(f.token,{expectedVersion:f.store.get(f.run.id).version,stage,pendingWork:[]});const saved=f.review.markRunReady(f.token,r.id);assert.equal(saved.status,'draft');assert.equal(f.store.get(f.run.id).status,'ready_for_review');assert.equal(f.review.get(r.id).status,'ready_for_review');assert.equal(f.store.cutoff(config.agent_id),f.run.end)});
test('approval expires when validation is older than one day',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});f.review.now=()=>now+86400001;await assert.rejects(f.review.decide(r.id,{expectedHash:r.hash,decision:'approve',authContext:human}),/expired/)});

test('authorised origin-bound HTTP approval records the exact human decision',async t=>{const f=fixture(t),r=f.review.saveDraft(f.token,{...f.options,evidence:f.evidence,attestation:f.attest()});const server=createReviewServer({review:f.review,authenticateRequest:async()=>human,origin:'http://127.0.0.1'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>server.close());const url=`http://127.0.0.1:${server.address().port}/reports/${r.id}/decision`;const response=await fetch(url,{method:'POST',redirect:'manual',headers:{'content-type':'application/x-www-form-urlencoded',origin:'http://127.0.0.1'},body:new URLSearchParams({expectedHash:r.hash,decision:'approve',comments:'Reviewed test fixture.'})});assert.equal(response.status,303);assert.equal(f.review.get(r.id).status,'approved')});
